config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: [:index, :new, :create, :show]
  resources :questions do
    resources :answers, only: :create
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # def new
  #   @answer = Answer.new
  # end

  def create
    answer = Answer.create(answer_params)
    redirect_to "/questions/#{answer.question.id}"
  end

  private
  def answer_params
    params.require(:answer).permit(:name, :content).merge(question_id: params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    Question.create(question_params)
    redirect_to action
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers
  end

  private
    def question_params
      params.require(:question).permit(:title, :content, :name)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="header">
        <div class="header__logo">
          <%= link_to 'TechChat', root_path %>
        </div>
        <div class="header__submit">
          <%= link_to '質問する', new_question_path %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<div class="contents">
  <% @questions.each do |question| %>
    <div class="content-question">
      <div class="content-question__comments">
        <div class="content-question__comments__num">
          0
        </div>
        <div class="content-question__comments__com">
          comments
        </div>
      </div>
      <div class="content-question__main">
        <div class="question-header">
          <div class="question-header__title">
            <%= link_to question.title, question_path(question.id) %>
          </div>
          <div class="question-header__name">
            <%= question.name %>
          </div>
        </div>
        <div class="question-main">
          <div class="question-main__content">
            <%= question.content %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="form-page">
  <div class="form-main">
    <div class="form-top"></div>
    <div class="form-bottom">
      <div class="forms">
        <%= form_with(model: @question, local: true) do |form| %>
          <div class="input-items">
            <div class="input-items__title">
              <%= form.text_field :title, placeholder: "タイトル" %><br>
            </div>
            <div class="input-items__content">
              <%= form.text_area :content, placeholder: "質問内容" %><br>
            </div>
            <div class="input-items__name">
              <%= form.text_field :name, placeholder: "投稿者名" %><br>
            </div>
            <div class="input-items__submit">
              <%= form.submit "POST" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
タイトル：<%= @question.title %><br>
質問内容：<%= @question.content %><br>
投稿者名：<%= @question.name %><br>

<%= form_with(model: [@question, @answer], local: true) do |form| %><br>
  <%= form.text_area :content, placeholder: '回答する' %><br>
  <%= form.text_field :name, placeholder: '投稿者名' %><br>
  <%= form.submit 'POST' %><br>
<% end %>

<% @answers.each do |answer| %>
  回答：<%= answer.content %><br>
  投稿者名：<%= answer.name %><br><br>
<% end %>